### ISSUE TITLE
Add dark Mode to a website

### ISSUE THREAD

**Issue by sinhasamarth** [Hackclub-CGC/Hackclub-CGC-website#23]
There is not any dark mode on the website. We need a toggle button that switches between  dark mode and light mode

**Comment by DeepanshuGOYAL05** [comment]
If you will get code for dark mode, help me too in this!!

**Comment by PrasannaBH** [comment]
Hey can i work on this ??

**Comment by sinhasamarth** [comment]
Sure @PrasannaBH you can go ahead

**Comment by PrasannaBH** [comment]
@sinhasamarth i tried running the index.php but its giving me error "Parse error: syntax error, unexpected '{' on line 157" same with contact-us.php on line 93 i am not really comfortable with PHP so can you please fix that beacause of that i am not able to verify my code

**Comment by sinhasamarth** [comment]
Hey @PrasannaBH You can open a issue OR our PHP DEVELOPER WILL FIX IT SOON

**Comment by sinhasamarth** [comment]
Hey @PrasannaBH Now it has fixed can you try again and sorry for inconvenience

**Comment by spacemonkey1101** [comment]
is this open?

**Comment by sinhasamarth** [comment]
Hii @spacemonkey1101 you can work too

**Comment by spacemonkey1101** [comment]
Hey I submitted the PR
