### ISSUE TITLE
Captcha Implementation in  forms make sure you use Google Captcha (INVISIBLE Version)

### ISSUE THREAD

**Issue by sinhasamarth** [Hackclub-CGC/Hackclub-CGC-website#24]
Captcha in forms make sure you use Google Captcha (INVISIBLE Version) in register.html, index.php and contact-us.php

**Comment by DeepanshuGOYAL05** [comment]
Can you provide the link for live version of this?

**Comment by sinhasamarth** [comment]
yes sure http://hackclubcgc.tech/

**Comment by DeepanshuGOYAL05** [comment]
You should mention it in readme file

**Comment by sinhasamarth** [comment]
thanks for your suggestion but It's already mentioned

**Comment by DeepanshuGOYAL05** [comment]
Ohh Okay, you can directly mention link text. It will be more visible and one suggestion you can add a feature that your website will always open it in new tab whenever user clicks on tahat

**Comment by sinhasamarth** [comment]
Hey, @DeepanshuGOYAL05 thanks for your suggestion I have changed the readme file now you can check if it is working in a new tab or not?

**Comment by Samarth-Sinha-V-2** [comment]
Can I do this task I am familiar with Captcha implementation

**Comment by sinhasamarth** [comment]
Ya you can @Samarth-Sinha-V-2

**Comment by Samarth-Sinha-V-2** [comment]
Thanks
