### ISSUE TITLE
Navigation Bar is not responsive

### ISSUE THREAD

**Issue by sinhasamarth** [Hackclub-CGC/Hackclub-CGC-website#25]
The navigation bar that contains menu bar and the logo is not responsive in all the screen size

**Comment by coded1guy** [comment]
hey @sinhasamarth can I help you to fix this.

**Comment by arjuna1729** [comment]
Yeah ! Go ahead

**Comment by sinhasamarth** [comment]
Hey @coded1guy if you are comfortable with bootstrap them go ahead.

**Comment by coded1guy** [comment]
@sinhasamarth how do you want it(the nav) to be like

**Comment by sinhasamarth** [comment]
Can you make navbar like this website is having
https://www.codechefvit.com
