### ISSUE TITLE
Redesign bottom Footer 

### ISSUE THREAD

**Issue by sinhasamarth** [Hackclub-CGC/Hackclub-CGC-website#27]
Hii buddy i need to redesign the footer part of the website because the current one looks that much cool only the bottom Footer.

**Comment by tahseenzahra** [comment]
Hi! @sinhasamarth is there any particular design for footer that you like if so please share it.

**Comment by sinhasamarth** [comment]
hey @tahseenzahra  we believe in creativity so you **can design as you like** but please note that it must look a little bit professional

**Comment by tahseenzahra** [comment]
ok

**Comment by sakshi006** [comment]
Hey, can i work on this?

**Comment by sinhasamarth** [comment]
Sorry @sakshi006 it's already assigned to @tahseenzahra if it's possible then you can collaborate with each other ans create an amazing design.

**Comment by tahseenzahra** [comment]
![SharedScreenshot](https://user-images.githubusercontent.com/54817285/95674345-0a0eb480-0bc9-11eb-8ab7-ef6d6ad8ebc0.jpg)
see these which one looks good to you
