### ISSUE TITLE
Add SEO Meta description and meta tags 

### ISSUE THREAD

**Issue by sinhasamarth** [Hackclub-CGC/Hackclub-CGC-website#33]
Add SEO Meta description and meta tags  on index.php and contact-us.php page

**Comment by Samarth-Sinha-V-2** [comment]
Can I work on this ?

**Comment by Samarth-Sinha-V-2** [comment]
I have done many seo task

**Comment by sinhasamarth** [comment]
Yes Sure

**Comment by Samarth-Sinha-V-2** [comment]
#35 #34 

I have created two pull request can you review them

**Comment by sinhasamarth** [comment]
Thank @Samarth-Sinha-V-2 I have merged it
